CREATE TABLE frage (id INT PRIMARY KEY, korrekte_antwort_id INT, frage text);
CREATE TABLE frage_antwort(frage_id INT, antwort_id INT, PRIMARY KEY (frage_id, antwort_id));
CREATE TABLE antwort (id INT PRIMARY KEY, antwort text);

ALTER TABLE FRAGE_ANTWORT ADD FOREIGN KEY (FRAGE_ID) REFERENCES FRAGE (ID);
ALTER TABLE FRAGE_ANTWORT ADD FOREIGN KEY (ANTWORT_ID) REFERENCES ANTWORT (ID);
ALTER TABLE FRAGE ADD FOREIGN KEY (KORREKTE_ANTWORT_ID) REFERENCES ANTWORT (ID);
